name: Code Quality

on:
  push:
    branches: [ "AddGithubAction", "staging", "main" ]
  pull_request:
    branches: [ "AddGithubAction", "staging", "main" ]

jobs:
  code-quality:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, libxml

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: PHP Code Style (PHP CS Fixer)
      run: |
        composer require friendsofphp/php-cs-fixer --dev
        ./vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: PHP Static Analysis (PHPStan)
      run: |
        composer require phpstan/phpstan --dev
        ./vendor/bin/phpstan analyse app tests

    - name: Security Check
      run: |
        composer require enlightn/security-checker --dev
        ./vendor/bin/security-checker security:check
